version: '3.1'

services:
  app:
    image: 'money-transfer:latest'
    build:
      context: .
    container_name: 'money-transfer'
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    environment:
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Transfer
    restart: always

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Transfer
    restart: always